import type {
  Case,
  Evidence,
  Suspect,
  TimelineEvent,
  DashboardStats,
  Alert,
  ChatMessage,
  Report,
} from '@/types';

// -----------------------------------------------
// Mock Cases
// -----------------------------------------------
export const mockCases: Case[] = [
  {
    id: 'case-001',
    caseNumber: 'PAN-2026-0047',
    title: 'Armed Robbery – Central Station',
    description:
      'Armed robbery at Central Station at 14:32. Two suspects fled on foot through the north exit. Victim sustained minor injuries.',
    status: 'active',
    priority: 'critical',
    category: 'Armed Robbery',
    location: 'Central Station, Platform 4',
    incidentDate: '2026-06-28T14:32:00Z',
    createdAt: '2026-06-28T15:00:00Z',
    updatedAt: '2026-06-30T09:15:00Z',
    createdBy: 'Det. Sarah Kim',
    assignedTo: ['user-001', 'user-002'],
    evidenceCount: 14,
    suspects: 2,
    aiProcessed: true,
    confidenceScore: 87,
    tags: ['robbery', 'armed', 'station', 'cctv'],
  },
  {
    id: 'case-002',
    caseNumber: 'PAN-2026-0043',
    title: 'Homicide Investigation – Riverside',
    description:
      'Victim found unresponsive near Riverside Park. Evidence suggests altercation. Multiple cameras in the area being analyzed.',
    status: 'active',
    priority: 'critical',
    category: 'Homicide',
    location: 'Riverside Park, East Entrance',
    incidentDate: '2026-06-25T23:10:00Z',
    createdAt: '2026-06-26T00:30:00Z',
    updatedAt: '2026-06-30T11:00:00Z',
    createdBy: 'Det. Marcus Webb',
    assignedTo: ['user-002', 'user-003'],
    evidenceCount: 28,
    suspects: 1,
    aiProcessed: true,
    confidenceScore: 72,
    tags: ['homicide', 'park', 'nighttime'],
  },
  {
    id: 'case-003',
    caseNumber: 'PAN-2026-0039',
    title: 'Vehicle Theft Ring – Port District',
    description:
      'Organized vehicle theft operation operating in port district. Drone footage captured multiple vehicles being loaded onto containers.',
    status: 'active',
    priority: 'high',
    category: 'Organized Crime',
    location: 'Port District, Warehouse Zone B',
    incidentDate: '2026-06-20T03:00:00Z',
    createdAt: '2026-06-20T08:00:00Z',
    updatedAt: '2026-06-29T16:45:00Z',
    createdBy: 'Sgt. Diana Torres',
    assignedTo: ['user-001', 'user-004'],
    evidenceCount: 42,
    suspects: 6,
    aiProcessed: true,
    confidenceScore: 91,
    tags: ['vehicle', 'organized', 'drone', 'port'],
  },
  {
    id: 'case-004',
    caseNumber: 'PAN-2026-0052',
    title: 'Assault – Waterfront Bar',
    description: 'Aggravated assault outside Waterfront Bar. Body camera footage obtained from responding officers.',
    status: 'pending',
    priority: 'medium',
    category: 'Assault',
    location: 'Waterfront District, 5th Ave',
    incidentDate: '2026-06-29T22:45:00Z',
    createdAt: '2026-06-29T23:30:00Z',
    updatedAt: '2026-06-30T08:00:00Z',
    createdBy: 'Off. Chris Patel',
    assignedTo: ['user-003'],
    evidenceCount: 5,
    suspects: 3,
    aiProcessed: false,
    confidenceScore: 0,
    tags: ['assault', 'bar', 'bodycam'],
  },
  {
    id: 'case-005',
    caseNumber: 'PAN-2026-0031',
    title: 'Drug Distribution Network',
    description: 'Ongoing surveillance of suspected drug distribution operation. Cross-camera tracking of known associates.',
    status: 'active',
    priority: 'high',
    category: 'Narcotics',
    location: 'Downtown Core, Multiple Locations',
    incidentDate: '2026-06-01T00:00:00Z',
    createdAt: '2026-06-01T09:00:00Z',
    updatedAt: '2026-06-30T10:30:00Z',
    createdBy: 'Det. Sarah Kim',
    assignedTo: ['user-001', 'user-002', 'user-004'],
    evidenceCount: 87,
    suspects: 11,
    aiProcessed: true,
    confidenceScore: 83,
    tags: ['narcotics', 'surveillance', 'network'],
  },
  {
    id: 'case-006',
    caseNumber: 'PAN-2026-0018',
    title: 'Cybercrime – Financial Fraud',
    description:
      'Multi-million dollar financial fraud operation. Suspects identified via ATM camera networks and cross-referenced with transaction data.',
    status: 'closed',
    priority: 'high',
    category: 'Cybercrime',
    location: 'Financial District',
    incidentDate: '2026-04-15T10:00:00Z',
    createdAt: '2026-04-15T14:00:00Z',
    updatedAt: '2026-06-10T17:00:00Z',
    createdBy: 'Det. Marcus Webb',
    assignedTo: ['user-002'],
    evidenceCount: 53,
    suspects: 4,
    aiProcessed: true,
    confidenceScore: 96,
    tags: ['fraud', 'financial', 'atm', 'closed'],
  },
];

// -----------------------------------------------
// Mock Evidence
// -----------------------------------------------
export const mockEvidence: Evidence[] = [
  {
    id: 'ev-001',
    caseId: 'case-001',
    filename: 'station_cam4_20260628_1430.mp4',
    originalName: 'Station Camera 4 – 28 Jun 14:30',
    type: 'video',
    size: 284_000_000,
    duration: 1800,
    resolution: '1920x1080',
    fps: 30,
    fileUrl: '/evidence/ev-001.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/ev001/320/180',
    status: 'processed',
    uploadedAt: '2026-06-28T15:10:00Z',
    processedAt: '2026-06-28T16:00:00Z',
    uploadedBy: 'Det. Sarah Kim',
    metadata: {
      captureDate: '2026-06-28',
      captureTime: '14:30:00',
      cameraId: 'CAM-STN-004',
      cameraLocation: 'Central Station Platform 4',
    },
    aiResults: {
      processingId: 'proc-001',
      evidenceId: 'ev-001',
      status: 'completed',
      progress: 100,
      startedAt: '2026-06-28T15:15:00Z',
      completedAt: '2026-06-28T16:00:00Z',
      objects: [],
      persons: [],
      events: [],
      synopsis:
        'Two suspects approach the victim at 14:32:14. A confrontation lasting 47 seconds is observed. Suspects flee northward at 14:33:01. Clear facial features captured on both suspects.',
      confidence: 92,
      processingModels: ['YOLOv8', 'ByteTrack', 'FastReID'],
    },
    tags: ['platform', 'suspects', 'robbery'],
    notes: 'Primary evidence. High confidence facial capture on suspect 1 at 14:32:28.',
    hash: 'sha256:a1b2c3d4e5f6...',
  },
  {
    id: 'ev-002',
    caseId: 'case-001',
    filename: 'station_cam2_20260628_1430.mp4',
    originalName: 'Station Camera 2 – Overview',
    type: 'video',
    size: 196_000_000,
    duration: 1800,
    resolution: '1920x1080',
    fps: 25,
    fileUrl: '/evidence/ev-002.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/ev002/320/180',
    status: 'processed',
    uploadedAt: '2026-06-28T15:12:00Z',
    processedAt: '2026-06-28T16:15:00Z',
    uploadedBy: 'Det. Sarah Kim',
    metadata: {
      captureDate: '2026-06-28',
      captureTime: '14:30:00',
      cameraId: 'CAM-STN-002',
      cameraLocation: 'Central Station Main Concourse',
    },
    tags: ['overview', 'concourse'],
    notes: 'Shows suspects entering station 4 minutes before incident.',
    hash: 'sha256:b2c3d4e5f6a7...',
  },
  {
    id: 'ev-003',
    caseId: 'case-001',
    filename: 'officer_bodycam_001.mp4',
    originalName: 'Off. Rodriguez Body Camera',
    type: 'bodycam',
    size: 98_000_000,
    duration: 900,
    resolution: '1280x720',
    fps: 30,
    fileUrl: '/evidence/ev-003.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/ev003/320/180',
    status: 'processed',
    uploadedAt: '2026-06-28T15:30:00Z',
    processedAt: '2026-06-28T16:45:00Z',
    uploadedBy: 'Sgt. M. Rodriguez',
    metadata: {
      captureDate: '2026-06-28',
      captureTime: '14:45:00',
      deviceInfo: 'Axon Body 3',
    },
    tags: ['bodycam', 'scene', 'victim'],
    notes: 'Captures immediate aftermath. Victim statement. North exit route.',
    hash: 'sha256:c3d4e5f6a7b8...',
  },
  {
    id: 'ev-004',
    caseId: 'case-002',
    filename: 'riverside_north_gate_20260625.mp4',
    originalName: 'Riverside North Gate Camera',
    type: 'video',
    size: 412_000_000,
    duration: 3600,
    resolution: '4K',
    fps: 30,
    fileUrl: '/evidence/ev-004.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/ev004/320/180',
    status: 'processed',
    uploadedAt: '2026-06-26T06:00:00Z',
    processedAt: '2026-06-26T10:00:00Z',
    uploadedBy: 'Det. Marcus Webb',
    metadata: {
      captureDate: '2026-06-25',
      captureTime: '22:00:00',
      cameraId: 'CAM-PARK-N01',
      cameraLocation: 'Riverside Park North Gate',
    },
    tags: ['park', 'gate', 'night'],
    notes: 'Suspect seen entering park at 22:54. Exits at 23:18.',
    hash: 'sha256:d4e5f6a7b8c9...',
  },
  {
    id: 'ev-005',
    caseId: 'case-003',
    filename: 'drone_port_survey_20260620.mp4',
    originalName: 'Drone Survey – Port Zone B',
    type: 'drone',
    size: 1_200_000_000,
    duration: 7200,
    resolution: '4K',
    fps: 30,
    fileUrl: '/evidence/ev-005.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/ev005/320/180',
    status: 'processed',
    uploadedAt: '2026-06-20T09:00:00Z',
    processedAt: '2026-06-20T15:00:00Z',
    uploadedBy: 'Sgt. Diana Torres',
    metadata: {
      captureDate: '2026-06-20',
      captureTime: '03:00:00',
      deviceInfo: 'DJI Matrice 350 RTK',
      gpsCoordinates: { lat: 37.7749, lng: -122.4194 },
    },
    tags: ['drone', 'port', 'vehicles', 'containers'],
    notes: 'Captures 6 suspects loading 14 vehicles. License plates partially visible.',
    hash: 'sha256:e5f6a7b8c9d0...',
  },
];

// -----------------------------------------------
// Mock Suspects
// -----------------------------------------------
export const mockSuspects: Suspect[] = [
  {
    id: 'sus-001',
    caseId: 'case-001',
    label: 'Suspect Alpha',
    description: 'Male, ~30-35 yrs, dark jacket, cap. Primary aggressor during robbery.',
    attributes: {
      gender: 'Male',
      ageRange: '30-35',
      clothing: ['Dark jacket', 'Baseball cap', 'Dark trousers'],
      accessories: ['Backpack'],
    },
    trackIds: [
      { evidenceId: 'ev-001', trackId: 'TRK-001' },
      { evidenceId: 'ev-002', trackId: 'TRK-007' },
    ],
    firstSeen: '2026-06-28T14:28:00Z',
    lastSeen: '2026-06-28T14:35:00Z',
    appearances: 2,
    cameras: ['CAM-STN-004', 'CAM-STN-002'],
    confidenceScore: 94,
    thumbnailUrl: 'https://picsum.photos/seed/sus001/80/80',
    status: 'unidentified',
    notes: 'Clear facial capture at 14:32:28. Biometric analysis in progress.',
  },
  {
    id: 'sus-002',
    caseId: 'case-001',
    label: 'Suspect Beta',
    description: 'Male, ~25-30 yrs, grey hoodie, jeans. Lookout role observed.',
    attributes: {
      gender: 'Male',
      ageRange: '25-30',
      clothing: ['Grey hoodie', 'Blue jeans', 'White sneakers'],
    },
    trackIds: [
      { evidenceId: 'ev-001', trackId: 'TRK-002' },
      { evidenceId: 'ev-002', trackId: 'TRK-008' },
    ],
    firstSeen: '2026-06-28T14:28:00Z',
    lastSeen: '2026-06-28T14:35:00Z',
    appearances: 2,
    cameras: ['CAM-STN-004', 'CAM-STN-002'],
    confidenceScore: 88,
    thumbnailUrl: 'https://picsum.photos/seed/sus002/80/80',
    status: 'unidentified',
  },
  {
    id: 'sus-003',
    caseId: 'case-002',
    label: 'Person of Interest 1',
    description: 'Male, ~40-45 yrs, dark coat. Last seen near east entrance.',
    attributes: {
      gender: 'Male',
      ageRange: '40-45',
      clothing: ['Dark coat', 'Dark trousers'],
    },
    trackIds: [{ evidenceId: 'ev-004', trackId: 'TRK-001' }],
    firstSeen: '2026-06-25T22:54:00Z',
    lastSeen: '2026-06-25T23:18:00Z',
    appearances: 1,
    cameras: ['CAM-PARK-N01'],
    confidenceScore: 71,
    thumbnailUrl: 'https://picsum.photos/seed/sus003/80/80',
    status: 'unidentified',
    notes: 'Entered park 24 minutes before victim found. Exited 8 minutes after estimated time of death.',
  },
];

// -----------------------------------------------
// Mock Timeline Events
// -----------------------------------------------
export const mockTimeline: TimelineEvent[] = [
  {
    id: 'tl-001',
    caseId: 'case-001',
    timestamp: '2026-06-28T14:28:14Z',
    title: 'Suspects Arrive at Station',
    description: 'Two suspects identified entering Central Station via south entrance.',
    type: 'person_detected',
    source: 'CAM-STN-002',
    evidenceId: 'ev-002',
    suspects: ['sus-001', 'sus-002'],
    location: 'South Entrance',
    confidence: 91,
    significance: 'high',
    verified: true,
    frameUrl: 'https://picsum.photos/seed/frame001/640/360',
  },
  {
    id: 'tl-002',
    caseId: 'case-001',
    timestamp: '2026-06-28T14:31:48Z',
    title: 'Suspects Approach Platform 4',
    description: 'Suspects move toward platform 4 where victim is waiting.',
    type: 'movement',
    source: 'CAM-STN-004',
    evidenceId: 'ev-001',
    suspects: ['sus-001', 'sus-002'],
    location: 'Platform 4 Access',
    confidence: 95,
    significance: 'critical',
    verified: true,
    frameUrl: 'https://picsum.photos/seed/frame002/640/360',
  },
  {
    id: 'tl-003',
    caseId: 'case-001',
    timestamp: '2026-06-28T14:32:14Z',
    title: 'Robbery Initiated',
    description: 'Suspect Alpha confronts victim. Object (firearm) detected in hand.',
    type: 'weapon',
    source: 'CAM-STN-004',
    evidenceId: 'ev-001',
    suspects: ['sus-001'],
    location: 'Platform 4',
    confidence: 89,
    significance: 'critical',
    verified: true,
    frameUrl: 'https://picsum.photos/seed/frame003/640/360',
  },
  {
    id: 'tl-004',
    caseId: 'case-001',
    timestamp: '2026-06-28T14:33:01Z',
    title: 'Suspects Flee – North Exit',
    description: 'Both suspects flee northward through emergency exit.',
    type: 'movement',
    source: 'CAM-STN-004',
    evidenceId: 'ev-001',
    suspects: ['sus-001', 'sus-002'],
    location: 'North Exit',
    confidence: 97,
    significance: 'critical',
    verified: true,
    frameUrl: 'https://picsum.photos/seed/frame004/640/360',
  },
  {
    id: 'tl-005',
    caseId: 'case-001',
    timestamp: '2026-06-28T14:45:22Z',
    title: 'Officer Rodriguez Arrives',
    description: 'First responding officer arrives at scene. Body camera activated.',
    type: 'manual',
    source: 'Body Camera',
    evidenceId: 'ev-003',
    location: 'Platform 4',
    confidence: 100,
    significance: 'medium',
    verified: true,
  },
];

// -----------------------------------------------
// Mock Dashboard Stats
// -----------------------------------------------
export const mockDashboardStats: DashboardStats = {
  activeCases: 4,
  totalEvidence: 229,
  processingQueue: 7,
  alertsToday: 3,
  suspectsTracked: 23,
  reportsGenerated: 18,
  aiAccuracy: 91.4,
  systemHealth: 'operational',
};

// -----------------------------------------------
// Mock Alerts
// -----------------------------------------------
export const mockAlerts: Alert[] = [
  {
    id: 'alert-001',
    caseId: 'case-001',
    type: 'suspect_match',
    severity: 'critical',
    title: 'Suspect Match Detected',
    message: 'Suspect Alpha (PAN-2026-0047) matched with CCTV footage from adjacent street camera 45 minutes after incident.',
    read: false,
    createdAt: '2026-06-28T15:22:00Z',
  },
  {
    id: 'alert-002',
    caseId: 'case-003',
    type: 'processing_complete',
    severity: 'info',
    title: 'AI Processing Complete',
    message: 'Drone footage for PAN-2026-0039 fully processed. 6 suspects and 14 vehicles tracked.',
    read: false,
    createdAt: '2026-06-28T16:00:00Z',
  },
  {
    id: 'alert-003',
    caseId: 'case-002',
    type: 'new_evidence',
    severity: 'warning',
    title: 'New Evidence Uploaded',
    message: 'Forensic images from Riverside Park processed. AI analysis pending.',
    read: true,
    createdAt: '2026-06-27T09:00:00Z',
  },
];

// -----------------------------------------------
// Mock Chat Messages
// -----------------------------------------------
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-001',
    role: 'user',
    content: 'Who touched the backpack during the robbery?',
    timestamp: '2026-06-30T09:30:00Z',
  },
  {
    id: 'msg-002',
    role: 'assistant',
    content:
      'Based on my analysis of evidence ev-001 (Station Camera 4), **Suspect Alpha** was observed handling the victim\'s backpack at **14:32:28**. The interaction lasted approximately 12 seconds. Suspect Alpha reached for the backpack with their right hand while Suspect Beta maintained position 2.3 meters away as a lookout.\n\nNo other individuals made contact with the backpack in the reviewed footage.',
    timestamp: '2026-06-30T09:30:08Z',
    evidenceRefs: ['ev-001'],
    suspectRefs: ['sus-001', 'sus-002'],
    confidence: 92,
    processingTime: 1840,
  },
  {
    id: 'msg-003',
    role: 'user',
    content: 'Show me the suspect movements before the robbery',
    timestamp: '2026-06-30T09:31:00Z',
  },
  {
    id: 'msg-004',
    role: 'assistant',
    content:
      'I have reconstructed the suspect movement timeline prior to the incident:\n\n**14:28:14** — Both suspects enter via South Entrance (CAM-STN-002, 91% confidence)\n**14:29:02** — Suspects wait near ticketing area for 1 min 46 sec\n**14:30:48** — Suspects observe platform board. Movement toward Platform 4 begins.\n**14:31:48** — Suspects arrive at Platform 4 entrance (CAM-STN-004, 95% confidence)\n**14:32:14** — Robbery initiated\n\nThe 4-minute window between arrival and action suggests pre-planning and target selection.',
    timestamp: '2026-06-30T09:31:09Z',
    evidenceRefs: ['ev-001', 'ev-002'],
    suspectRefs: ['sus-001', 'sus-002'],
    timelineRefs: ['tl-001', 'tl-002', 'tl-003'],
    confidence: 89,
    processingTime: 2100,
  },
];

// -----------------------------------------------
// Mock Report
// -----------------------------------------------
export const mockReport: Report = {
  id: 'rpt-001',
  caseId: 'case-001',
  type: 'comprehensive',
  title: 'Forensic Intelligence Report – PAN-2026-0047',
  status: 'reviewed',
  generatedAt: '2026-06-30T10:00:00Z',
  generatedBy: 'AI Assistant (Gemini)',
  reviewedBy: 'Det. Sarah Kim',
  summary:
    'Armed robbery at Central Station on 28 June 2026 at 14:32. Two suspects identified via cross-camera analysis. Complete movement reconstruction from 14:28 to 14:35. High-confidence facial capture on primary suspect. Suspects fled via north exit.',
  sections: [
    {
      id: 'sec-001',
      title: 'Incident Summary',
      content:
        'On 28 June 2026 at approximately 14:32, an armed robbery occurred at Central Station Platform 4. The victim was approached by two suspects identified as Suspect Alpha and Suspect Beta...',
      order: 1,
      type: 'text',
    },
    {
      id: 'sec-002',
      title: 'Evidence Timeline',
      content: 'AI-reconstructed timeline of events based on synchronized camera feeds.',
      order: 2,
      type: 'timeline',
    },
    {
      id: 'sec-003',
      title: 'Suspect Profiles',
      content: 'Detailed profiles generated from cross-camera re-identification analysis.',
      order: 3,
      type: 'suspect_profile',
    },
  ],
  version: 2,
};
